backend:
  name: github
  repo: GlitchMahotsukai/GlitchMahotsukai.github.io
  branch: master

site_url: https://glitchmahotsukai.github.io/
display_url: https://glitchmahotsukai.github.io/

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/zh/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "作者", name: "author", widget: "string", default: "管理员" }
      - { label: "标签", name: "tags", widget: "list", default: ["文章"] }
      - { label: "封面图片", name: "image", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown", required: false }

  - name: "logs"
    label: "日志"
    folder: "content/zh/logs"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "正文", name: "body", widget: "markdown", required: false }

  - name: "media"
    label: "媒体"
    folder: "content/zh/media"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "正文", name: "body", widget: "markdown", required: false }

  - name: "posts-en"
    label: "Posts"
    folder: "content/en/posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Admin" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "logs-en"
    label: "Logs"
    folder: "content/en/logs"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false }

  - name: "media-en"
    label: "Media"
    folder: "content/en/media"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
